export const TRACK = 'TRACK';
export const UPDATE_LIST = 'UPDATE_LIST';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const ADD_TO_RECENT_SEARCHERS = 'ADD_TO_RECENT_SEARCHERS';
export const HISTORY_GOT_CLICKED = 'HISTORY_GOT_CLICKED';
export const CHANGE_VIEW_MODE = 'CHANGE_VIEW_MODE';